// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// ShareObjectWithCredsCreatedCode is the HTTP code returned for type ShareObjectWithCredsCreated
const ShareObjectWithCredsCreatedCode int = 201

/*ShareObjectWithCredsCreated A successful response.

swagger:response shareObjectWithCredsCreated
*/
type ShareObjectWithCredsCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewShareObjectWithCredsCreated creates ShareObjectWithCredsCreated with default headers values
func NewShareObjectWithCredsCreated() *ShareObjectWithCredsCreated {

	return &ShareObjectWithCredsCreated{}
}

// WithPayload adds the payload to the share object with creds created response
func (o *ShareObjectWithCredsCreated) WithPayload(payload string) *ShareObjectWithCredsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the share object with creds created response
func (o *ShareObjectWithCredsCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShareObjectWithCredsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ShareObjectWithCredsDefault Generic error response.

swagger:response shareObjectWithCredsDefault
*/
type ShareObjectWithCredsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShareObjectWithCredsDefault creates ShareObjectWithCredsDefault with default headers values
func NewShareObjectWithCredsDefault(code int) *ShareObjectWithCredsDefault {
	if code <= 0 {
		code = 500
	}

	return &ShareObjectWithCredsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the share object with creds default response
func (o *ShareObjectWithCredsDefault) WithStatusCode(code int) *ShareObjectWithCredsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the share object with creds default response
func (o *ShareObjectWithCredsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the share object with creds default response
func (o *ShareObjectWithCredsDefault) WithPayload(payload *models.Error) *ShareObjectWithCredsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the share object with creds default response
func (o *ShareObjectWithCredsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShareObjectWithCredsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
